// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

using StudioGhibliApi.Data.CharacterDbContext;

namespace StudioGhibliApi.Migrations
{
    [DbContext(typeof(CharacterContext))]
    [Migration("20210429200934_AddedCharacters")]
    partial class AddedCharacters
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("StudioGhibliApi.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilmId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilmName")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.ToTable("Character");
                });
#pragma warning restore 612, 618
        }
    }
}
